version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - HUGGINGFACE_API_TOKEN=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  # Replace with your actual HuggingFace token
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000  # For local development 